### ISSUE TITLE
Spacy 3 support for med7

### ISSUE THREAD

**Issue by ervivek** [kormilitzin/med7#10]
I am eagerly waiting for the med7 upgrade to spacy 3. After the release of spacy 3, performance of med7 become worse.
Please suggest any tentative timeline for spacy3 upgrade.

**Comment by kormilitzin** [comment]
@ervivek We are currently updating Med7, we anticipate it may take up to 4-5 weeks.

**Comment by ervivek** [comment]
any luck with spacy 3 support, current release has lots of performance issues.

**Comment by kormilitzin** [comment]
@ervivek Yes, please check the main page for a link to "en_core_med7_trf". It is based on RoBERTa and outperformed spaCy 2 performance. **However** it is still work in progress and some entities **may be missed**. We continue working on improving it. Any feedback will help improve it.
