### ISSUE TITLE
Cannot load en_core_med7_lg

### ISSUE THREAD

**Issue by carleyreardon3** [kormilitzin/med7#11]
Hi, I'm trying to load en_core_med7_lg using the following code:

nlp = spacy.load("en_core_med7_lg")

But I am getting this error:

OSError: [E053] Could not read config.cfg from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/en_core_med7_lg/en_core_med7_lg-0.0.3/config.cfg

I have made sure my spacy version is 2.3.5 and have successfully installed en_core_med7_lg using pip. What could be wrong?

P.S. I should add that I was able to load en_core_med7_trf with spacy 3.0.6, it's just this model that isn't loading

**Comment by kormilitzin** [comment]
@carleyreardon3 Thanks for reporting. It's a quite common error, or its very similar variations, you may find on the internet (e.g [here](https://github.com/explosion/spaCy/issues/7453), [here](https://github.com/github/hub/issues/2711) and [here](https://stackoverflow.com/questions/66149878/e053-could-not-read-config-cfg-resumeparser)). It's down to keeping a correct version of spaCy (<3+) and its all components.

If you are using colab and you don't control for the exact versions of packages, you will see this error. Even if you installed spaCy == 2.3.5, you should make sure that other dependencies are also compatible with this version of spaCy.

I tried to reproduce your error and I couldn't. Create a new instance of colab and run these:

`pip install -U pip setuptools wheel spacy==2.3.5`
`pip install https://med7.s3.eu-west-2.amazonaws.com/en_core_med7_lg.tar.gz`

```
import spacy
import en_core_med7_lg
med7 = en_core_med7_lg.load()
col_dict = {}
seven_colours = ['#e6194B', '#3cb44b', '#ffe119', '#ffd8b1', '#f58231', '#f032e6', '#42d4f4']
for label, colour in zip(med7.pipe_labels['ner'], seven_colours):
    col_dict[label] = colour

options = {'ents': med7.pipe_labels['ner'], 'colors':col_dict}

text = 'A patient was prescribed Magnesium hydroxide 400mg/5ml suspension PO of total 30ml bid for the next 5 days.'
doc = med7(text)

spacy.displacy.render(doc, style='ent', jupyter=True, options=options)

[(ent.text, ent.label_) for ent in doc.ents]
```

and you should see it working properly. Please be careful how you install `spaCy==2.3.5` and its dependencies. Let me know if you still have problems.

**Comment by carleyreardon3** [comment]
It looks like those pip install commands work, but now when I try the line:
med7 = en_core_med7_lg.load()

I get the error:
ModuleNotFoundError: No module named 'thinc.types'

I also get this error when instead doing:
med7 = spacy.load('en_core_med7_lg')

Any ideas what could be causing this?

Note: It looks like it is from somewhere within spacy-transformers, but I have installed this library already, due to a previous error.

**Comment by carleyreardon3** [comment]
Update: My problem was that my version of spacy-transformers was too new -- it needed to be the 0.6.2 version. I ran into another issue when down grading this dealing with a Rust compiler, which I solved using this: https://github.com/huggingface/transformers/issues/2831#issuecomment-600141935

**Comment by sahoodib** [comment]
"!pip install https://med7.s3.eu-west-2.amazonaws.com/en_core_med7_lg.tar.gz" this is giving me error as :- 
Collecting https://med7.s3.eu-west-2.amazonaws.com/en_core_med7_lg.tar.gz
  ERROR: HTTP error 403 while getting https://med7.s3.eu-west-2.amazonaws.com/en_core_med7_lg.tar.gz
ERROR: Could not install requirement https://med7.s3.eu-west-2.amazonaws.com/en_core_med7_lg.tar.gz because of HTTP error 403 Client Error: Forbidden for url: https://med7.s3.eu-west-2.amazonaws.com/en_core_med7_lg.tar.gz for URL https://med7.s3.eu-west-2.amazonaws.com/en_core_med7_lg.tar.gz
in google cola

**Comment by kormilitzin** [comment]
@sahoodib Thanks for letting me know about this error. We have moved all med7 models to Hugging Face hub: https://huggingface.co/kormilitzin/en_core_med7_lg

and https://huggingface.co/kormilitzin/en_core_med7_trf

Please follow their instructions how to install Med7.

**Comment by sahoodib** [comment]
@kormilitzin thank you
