### ISSUE TITLE
Tensorflow version or equivalent model

### ISSUE THREAD

**Issue by zweili** [kormilitzin/med7#2]
Is there anyway to run this model without using pytorch ? Or do you know any equivalent of such model running with tensorflow environment only ?
I need to avoid pytorch as I am working on a virtual machine using tensorflow. (conflicts of libraries etc. )

Thank you very much

**Comment by kormilitzin** [comment]
@zweili It's a good questions! However spaCy is fully compatible with TF/PyTorch, you can even run them side-by-side. Please see: https://spacy.io/usage/examples#keras
