### ISSUE TITLE
Dataset Required 

### ISSUE THREAD

**Issue by Siddhijain16** [kormilitzin/med7#21]
Hi @kormilitzin 
First of all thank you for this library its very useful.
I need your dataset is there any ways to get it. Please let me know.

**Comment by kormilitzin** [comment]
@Siddhijain16 Thank you for your kind words. The data used to develop the model was from [MIMIC-III](https://mimic.mit.edu/docs/gettingstarted/) (text notes) and the "[n2c2 2018 — Track 2: Adverse Drug Events and Medication Extraction in EHRs](https://portal.dbmi.hms.harvard.edu/projects/n2c2-2018-t2/)"

You should register on these websites and then you will be able to download the data sets. I hope it helps.
