### ISSUE TITLE
unable to download med7

### ISSUE THREAD

**Issue by teddyhla** [kormilitzin/med7#25]
hi,

I am not sure if the links are expired. I am unable to download med7, either with huggingface link or with your amazon aws link. Your attached colab notebook couldn't install either. So I dont think it is from my side. Could you have a look at this please? Thanks

I tried the huggingface link which is provided in your github readme and that results in this error 

`pip install https://huggingface.co/kormilitzin/en_core_med7_trf/resolve/main/en_core_med7_trf-any-py3-none-any.whl`

ERROR: Invalid requirement: 'en-core-med7-trf==any': Expected end or semicolon (after name and no valid version specifier)
    en-core-med7-trf==any

Try other alternatives given it looks like version issues
`pip install https://huggingface.co/kormilitzin/en_core_med7_trf/resolve/main/en_core_med7_trf.whl`
    
ERROR: en_core_med7_trf.whl is not a valid wheel filename.

This is the amazon aws tar link 
`pip install https://med7.s3.eu-west-2.amazonaws.com/en_core_med7_trf.tar.gz`

ERROR: HTTP error 403 while getting https://med7.s3.eu-west-2.amazonaws.com/en_core_med7_trf.tar.gz
ERROR: Could not install requirement https://med7.s3.eu-west-2.amazonaws.com/en_core_med7_trf.tar.gz because of HTTP error 403 Client Error: Forbidden for url: https://med7.s3.eu-west-2.amazonaws.com/en_core_med7_trf.tar.gz for URL https://med7.s3.eu-west-2.amazonaws.com/en_core_med7_trf.tar.gz

Thanks a lot

**Comment by kormilitzin** [comment]
@teddyhla thanks for your interest. This error is related to a new `pip`. You need to add `@` after the package name:

for the "trf" model:
`pip install "en-core-med7-trf @ https://huggingface.co/kormilitzin/en_core_med7_trf/resolve/main/en_core_med7_trf-any-py3-none-any.whl"`

for the "lg" model:
`pip install "en-core-med7-lg @ https://huggingface.co/kormilitzin/en_core_med7_lg/resolve/main/en_core_med7_lg-any-py3-none-any.whl"`


For more details, please see a similar thread: https://github.com/explosion/spaCy/issues/13599

**Comment by teddyhla** [comment]
yes. that works now. really amazing. thank you so much for your quick reply. Not a big deal but if useful for you, I can fork a repo and update the read me and send you a PR?  Obviously if you are planning to etc or not needed, that is also okay :) once again much appreciated.

**Comment by kormilitzin** [comment]
Thanks, that would be awesome if you could do it please.

**Comment by teddyhla** [comment]
PR sent. thanks

**Comment by teddyhla** [comment]
Hey I did a PR a while ago. Could you review ? Just because someone now
messaged me for similar problem :)
Thanks
T

---

**Comment by kormilitzin** [comment]
@teddyhla Apologise for my delayed reply. I checked and confirmed this PR. Is it OK now?
Thanks a lot for doing this. This is really helpful for the community.

**Comment by teddyhla** [comment]
Yes, it's fine. In the mean time, two users messaged me for the fix; which
i have shared.

are you doing anything further on this at the moment? You are based in
Oxford right?

Thanks again
T

---

**Comment by kormilitzin** [comment]
Thanks @teddyhla, really appreciate your time to help with this. At the moment the plan is to re-train and update the package to the most recent version of spaCy. Overall, we are exploring other approaches, such as local quantised LLMs for information extraction. Happy to stay in touch.
