### ISSUE TITLE
Please release the model architecture and training code too.

### ISSUE THREAD

**Issue by anuragvij264** [kormilitzin/med7#3]

**Comment by kormilitzin** [comment]
@anuragvij264 , the model is taken from the spaCy tutorial on NER: https://github.com/explosion/spaCy/blob/master/examples/training/train_new_entity_type.py

the development was a mixture of the code in above and using spaCy command line interface for NER training:
https://spacy.io/api/cli#train

**Comment by rozeappletree** [comment]
> @anuragvij264 , the model is taken from the spaCy tutorial on NER: https://github.com/explosion/spaCy/blob/master/examples/training/train_new_entity_type.py
> 
> the development was a mixture of the code in above and using spaCy command line interface for NER training:
> https://spacy.io/api/cli#train

Hey @kormilitzin the link above is not working https://github.com/explosion/spaCy/blob/master/examples/training/train_new_entity_type.py

**Comment by szkocot** [comment]
@rakesh4real It's probably from a different version of spaCy that current. You can find for example here: https://github.com/explosion/spaCy/blob/v2.3.x/examples/training/train_new_entity_type.py
