### ISSUE TITLE
Model is incompatible with version 2.3 of spaCy

### ISSUE THREAD

**Issue by snosrap** [kormilitzin/med7#4]
`UserWarning: [W031] Model 'en_core_med7_lg' (0.0.2) requires spaCy v2.2 and is incompatible with the current spaCy version (2.3.0).`

According to the [spaCy 2.3 release notes](https://spacy.io/usage/v2-3#incompat), models need to be retrained on the new version.

There's a [similar issue with SciSpacy](https://github.com/allenai/scispacy/issues/244).

**Comment by kormilitzin** [comment]
@snosrap Indeed! We haven't yet re-trainaed the model , but definitely will adapt it for the most recent spaCy versions. Thanks for reporting the bug.

**Comment by kormilitzin** [comment]
@snosrap Done! The model was re-trained and is now compatible with spaCy 2.3.2. Please check and report should you have any problems.
